spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=${STUDENT_SERVICE_URL:lb://student-service}
spring.cloud.gateway.routes[0].predicates[0]=Path=/students/**

spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=${COURSE_SERVICE_URL:lb://course-service}
spring.cloud.gateway.routes[1].predicates[0]=Path=/courses/**

spring.cloud.gateway.routes[2].id=enrollment-service
spring.cloud.gateway.routes[2].uri=${ENROLLMENT_SERVICE_URL:lb://enrollment-service}
spring.cloud.gateway.routes[2].predicates[0]=Path=/enrollments/**

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

